### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by whaaaley** [zaceno/zx-state#1]
I know this is new and probably still experimental, but do you have (or could you add) a quick setup example of how to use this with (probably) picodom?

**Comment by zaceno** [comment]
@whaaaley Updated the README with some basic (and less basic) examples + links to codepens. Does that explain it all well enough, or do you need more? I'm hesitant to do too much to document the api since (as you say) its still very experimental.

**Comment by zaceno** [comment]
@whaaaley I'll close for now, but feel free to get back to me if there's anything more you need! :)
